<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <Content Include="bin\Debug\net10.0\HMS.Modules.Identity.Infrastructure.deps.json" />
    <Content Include="obj\Debug\net10.0\HMS.Modules.Identity.Infrastructure.csproj.FileListAbsolute.txt" />
    <Content Include="obj\Debug\net10.0\HMS.Modules.Identity.Infrastructure.sourcelink.json" />
    <Content Include="obj\HMS.Modules.Identity.Infrastructure.csproj.nuget.dgspec.json" />
    <Content Include="obj\project.assets.json" />
  </ItemGroup>
  <ItemGroup>
    <None Include="bin\Debug\net10.0\HMS.Application.Abstractions.dll" />
    <None Include="bin\Debug\net10.0\HMS.Application.Abstractions.pdb" />
    <None Include="bin\Debug\net10.0\HMS.Contracts.dll" />
    <None Include="bin\Debug\net10.0\HMS.Contracts.pdb" />
    <None Include="bin\Debug\net10.0\HMS.Infrastructure.dll" />
    <None Include="bin\Debug\net10.0\HMS.Infrastructure.pdb" />
    <None Include="bin\Debug\net10.0\HMS.Modules.Identity.Application.dll" />
    <None Include="bin\Debug\net10.0\HMS.Modules.Identity.Application.pdb" />
    <None Include="bin\Debug\net10.0\HMS.Modules.Identity.Domain.dll" />
    <None Include="bin\Debug\net10.0\HMS.Modules.Identity.Domain.pdb" />
    <None Include="bin\Debug\net10.0\HMS.Modules.Identity.Infrastructure.dll" />
    <None Include="bin\Debug\net10.0\HMS.Modules.Identity.Infrastructure.pdb" />
    <None Include="bin\Debug\net10.0\HMS.SharedKernel.dll" />
    <None Include="bin\Debug\net10.0\HMS.SharedKernel.pdb" />
    <None Include="obj\Debug\net10.0\HMS.Modu.1F6BEA23.Up2Date" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Identity.Infrastructure.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Identity.Infrastructure.assets.cache" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Identity.Infrastructure.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Identity.Infrastructure.csproj.BuildWithSkipAnalyzers" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Identity.Infrastructure.csproj.CoreCompileInputs.cache" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Identity.Infrastructure.dll" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Identity.Infrastructure.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Identity.Infrastructure.pdb" />
    <None Include="obj\Debug\net10.0\refint\HMS.Modules.Identity.Infrastructure.dll" />
    <None Include="obj\Debug\net10.0\ref\HMS.Modules.Identity.Infrastructure.dll" />
    <None Include="obj\HMS.Modules.Identity.Infrastructure.csproj.nuget.g.props" />
    <None Include="obj\HMS.Modules.Identity.Infrastructure.csproj.nuget.g.targets" />
    <None Include="obj\project.nuget.cache" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HMS.Modules.Identity.Domain\HMS.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\HMS.Modules.Identity.Application\HMS.Modules.Identity.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\HMS.Infrastructure\HMS.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.86" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.12" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Integrations\" />
    <Folder Include="Persistence\Configurations\" />
    <Folder Include="Persistence\Migrations\" />
    <Folder Include="Queries\" />
    <Folder Include="Services\" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>