<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HMS.Modules.Maintenance.Domain\HMS.Modules.Maintenance.Domain.csproj" />
    <ProjectReference Include="..\HMS.Modules.Maintenance.Application\HMS.Modules.Maintenance.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\HMS.Infrastructure\HMS.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
