<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Include="obj\Debug\net10.0\.NETCoreApp,Version=v10.0.AssemblyAttributes.cs" />
    <Compile Include="obj\Debug\net10.0\HMS.Modules.Inventory.Domain.AssemblyInfo.cs" />
    <Compile Include="obj\Debug\net10.0\HMS.Modules.Inventory.Domain.GlobalUsings.g.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="bin\Debug\net10.0\HMS.Modules.Inventory.Domain.deps.json" />
    <Content Include="obj\Debug\net10.0\HMS.Modules.Inventory.Domain.csproj.FileListAbsolute.txt" />
    <Content Include="obj\Debug\net10.0\HMS.Modules.Inventory.Domain.sourcelink.json" />
    <Content Include="obj\HMS.Modules.Inventory.Domain.csproj.nuget.dgspec.json" />
    <Content Include="obj\project.assets.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="bin\Debug\net10.0\HMS.Modules.Inventory.Domain.dll" />
    <None Include="bin\Debug\net10.0\HMS.Modules.Inventory.Domain.pdb" />
    <None Include="bin\Debug\net10.0\HMS.SharedKernel.dll" />
    <None Include="bin\Debug\net10.0\HMS.SharedKernel.pdb" />
    <None Include="obj\Debug\net10.0\HMS.Modu.0453993F.Up2Date" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Inventory.Domain.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Inventory.Domain.assets.cache" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Inventory.Domain.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Inventory.Domain.csproj.BuildWithSkipAnalyzers" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Inventory.Domain.csproj.CoreCompileInputs.cache" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Inventory.Domain.dll" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Inventory.Domain.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Inventory.Domain.pdb" />
    <None Include="obj\Debug\net10.0\refint\HMS.Modules.Inventory.Domain.dll" />
    <None Include="obj\Debug\net10.0\ref\HMS.Modules.Inventory.Domain.dll" />
    <None Include="obj\HMS.Modules.Inventory.Domain.csproj.nuget.g.props" />
    <None Include="obj\HMS.Modules.Inventory.Domain.csproj.nuget.g.targets" />
    <None Include="obj\project.nuget.cache" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\HMS.SharedKernel\HMS.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entities\" />
    <Folder Include="Enums\" />
    <Folder Include="Errors\" />
    <Folder Include="Events\" />
    <Folder Include="Services\" />
    <Folder Include="ValueObjects\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
