<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <Content Include="bin\Debug\net10.0\HMS.Modules.Identity.Domain.deps.json" />
    <Content Include="obj\Debug\net10.0\HMS.Modules.Identity.Domain.csproj.FileListAbsolute.txt" />
    <Content Include="obj\Debug\net10.0\HMS.Modules.Identity.Domain.sourcelink.json" />
    <Content Include="obj\HMS.Modules.Identity.Domain.csproj.nuget.dgspec.json" />
    <Content Include="obj\project.assets.json" />
  </ItemGroup>
  <ItemGroup>
    <None Include="bin\Debug\net10.0\HMS.Modules.Identity.Domain.dll" />
    <None Include="bin\Debug\net10.0\HMS.Modules.Identity.Domain.pdb" />
    <None Include="bin\Debug\net10.0\HMS.SharedKernel.dll" />
    <None Include="bin\Debug\net10.0\HMS.SharedKernel.pdb" />
    <None Include="obj\Debug\net10.0\HMS.Modu.382BFD3D.Up2Date" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Identity.Domain.AssemblyInfoInputs.cache" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Identity.Domain.assets.cache" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Identity.Domain.csproj.AssemblyReference.cache" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Identity.Domain.csproj.BuildWithSkipAnalyzers" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Identity.Domain.csproj.CoreCompileInputs.cache" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Identity.Domain.dll" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Identity.Domain.GeneratedMSBuildEditorConfig.editorconfig" />
    <None Include="obj\Debug\net10.0\HMS.Modules.Identity.Domain.pdb" />
    <None Include="obj\Debug\net10.0\refint\HMS.Modules.Identity.Domain.dll" />
    <None Include="obj\Debug\net10.0\ref\HMS.Modules.Identity.Domain.dll" />
    <None Include="obj\HMS.Modules.Identity.Domain.csproj.nuget.g.props" />
    <None Include="obj\HMS.Modules.Identity.Domain.csproj.nuget.g.targets" />
    <None Include="obj\project.nuget.cache" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\HMS.SharedKernel\HMS.SharedKernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Enums\" />
    <Folder Include="Errors\" />
    <Folder Include="Events\" />
    <Folder Include="Services\" />
    <Folder Include="ValueObjects\" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>