<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HMS.Modules.FrontDesk.Domain\HMS.Modules.FrontDesk.Domain.csproj" />
    <ProjectReference Include="..\HMS.Modules.FrontDesk.Application\HMS.Modules.FrontDesk.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\HMS.Infrastructure\HMS.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
